### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by forivall** [ashutoshgngwr/noice#150]
### Describe the solution you'd like
Support playing noise on Chromecast devices

**Comment by ashutoshgngwr** [comment]
Leaving my notes from the past research about this feature.

- Chromecast doesn't support streaming local media files
- In order to stream local media, the sender application will need to host an HTTP server that outputs the media stream for the receiver application.
- In order to integrate this into Noice, we need to transform `PlaybackManager` into a generic interface. `CastPlaybackManager` can be one of its concrete implementations. In this case, `CastPlaybackManager` will be responsible for listening to the playback control events. Maintain a state of playbacks and combine all playbacks into a single stream for outputting it via the HTTP server.

**Comment by forivall** [comment]
I took a look at the two open source apps that support casting, and it looks like AntennaPod simply forwards the media file from the server where it was downloaded,  https://www.github.com/AntennaPod/AntennaPod/tree/develop/core%2Fsrc%2Fplay%2Fjava%2Fde%2Fdanoeh%2Fantennapod%2Fcore%2Fcast and VLC does launch its own server, but it's in c++, so... ¯\_(ツ)_/¯ https://github.com/videolan/vlc/blob/master/modules/stream_out/chromecast/cast.cpp

**Comment by ashutoshgngwr** [comment]
@forivall i am jumping around fences on which way to go. The former method is way more complex and requires refactoring (which I am personally tired of). Latter is simple to implement because then sender app could just send playback events and receiver app could do the actual playback. But then any change to Playback logic would need to be implemented twice. I was already planning on introducing a feature that would cause something like it (#144)

I guess I need to do a lot more research before starting to smash my keys on this one. :sweat_smile:
