### ISSUE TITLE
Buggy playback after internal rename wind_in_chimes_of_shells -> wind_chimes_of_shells

### ISSUE THREAD

**Issue by refola** [ashutoshgngwr/noice#168]
### Describe the bug
One of the presets I made doesn't turn its play button into a stop button when I play it, and one of its tracks isn't playing.

### To Reproduce
1. In an unspecified earlier version (< 0.7.0) of Noice, save a preset which includes the "Wind in chimes of shells" track.
2. Upgrade to Noice 0.7.0.
3. Press the play button by the saved preset from the Presets list.
4. Listen for the wind in chimes of shells; it's not there.
5. Try to press the stop icon, but the icon is stuck on play.

### Expected behavior
After pressing the play button to play the preset, all tracks in the preset should play. Additionally, the play button should change to a stop button, just like for other presets.

### Others
 - Device: OnePlus One
 - Android Version: Pie (LineageOS)
- Noice version: 0.7.0, from F-Droid

### Additional info

it looks like the track in question got renamed from `wind_in_chimes_of_shells` to `wind_chimes_of_shells`. This is based on names in the presets JSON data as viewed with "Preferences Manager" from F-Droid. I compared the old preset with a new one with just "Wind in chimes of shells". Also, manually removing `_in` from the buggy preset fixes it.

I suspect a `grep --recursive "wind_chimes_of_shells"` followed by a `git blame "$FILE_THAT_GREP_FINDS" | grep "wind_chimes_of_shells"` will find the problem commit. I would've done it myself, but GitHub was being excruciatingly slow at letting me clone this repo (`Receiving objects:  13% (539/4023), 9.54 MiB | 23.00 KiB/s` in the 8 minutes it's been downloading).

**Comment by ashutoshgngwr** [comment]
@refola the repository is big in size due to binary files. Take your time. I'll try to track down its origin meanwhile.

**Comment by ashutoshgngwr** [comment]
@refola The bug is understandable. With event based communication between playback service and UI, the service will be crashing in background while UI isn't affected. The key did change in 0.2.x and 0.3.x and it wasn't intentional. If you're on it, please commit the fix. Otherwise let me know and I'll commit it myself.

#### 0.2.x Sound Library https://github.com/ashutoshgngwr/noice/blob/b876cec8abd13e59d0e71d81d9b5bc791f522156/app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt#L300

#### 0.3.x Sound Library
https://github.com/ashutoshgngwr/noice/blob/3d68e86b3adfa841598afd1546cdb18c72c9df06/app/src/main/java/com/github/ashutoshgngwr/noice/sound/Sound.kt#L43

**Comment by refola** [comment]
> If you're on it, please commit the fix. Otherwise let me know and I'll commit it myself.

1. I'm not on it. I gave up on downloading the repo (you seem to have found the source line either way). Please commit it yourself.

2. The fix needs to handle both the old and the new names. Merely changing it back will result in the same broken behavior for any preset made with the new "Wind in chimes of shells" track. Maybe you can have Noice normalize both versions to

**Comment by ashutoshgngwr** [comment]
I'll see what I can do but temporary migration code is unlikely. We can never be sure whether to phase out migration code because users more often keep using older versions.

Other similar issues were introduced  in the same bump as well. #110 #117 This fix have no phase out strategy either. This have to remain their ad-infinitum.

**Comment by refola** [comment]
> I'll see what I can do but temporary migration code is unlikely. We can never be sure whether to phase out migration code because users more often keep using older versions.

I'd assume that after a year or so most users either upgraded or won't upgrade. 

Reading #169, it looks like your fix only works for users who upgrade directly from older versions. Users who made a preset with "wind in chimes of shells" in version 0.7.0 and then upgrade will have the same problem in reverse.

> #110 #117 

It looks like those ones also have no compatibility with the buggy version(s). But in that case I remember crashes prevented creating different-schema presets in at least one version.

> On a side note, you're the first one to report this and we don't have a huge user base.

Thanks. Sometimes I'm good at hitting edge cases. ;)

**Comment by ashutoshgngwr** [comment]
Aw crap! I need to revert that fix. I forgot to consider the release gap. 0.2.x is ancient now. Its already phased out. I don't know how you came across this bug. The user base is already small and since we've had no reports prior to this, we don't even need a fix. :neutral_face: 

> Thanks. Sometimes I'm good at hitting edge cases. ;)

Yeah, thanks for the report but no thanks. :sweat_smile:

_Its true, ladies and gentlemen. Sometimes I think like a sheep._

**Comment by refola** [comment]
> I don't know how you came across this bug.

I had an old saved preset that in which I must've not noticed the missing "wind in chimes of shells" sound. I only noticed the issue when I was going thru and playing all my presets.

> The user base is already small and since we've had no reports prior to this, we don't even need a fix. neutral_face

Fair enough. It's a much more minor bug than the entire app crashing. My perfectionism doesn't like this going unfixed, but my lazy side is happy that I don't have to change my preset back. :shrug:
