### ISSUE TITLE
Use Ogg Vorbis codec for sound files instead of MP3

### ISSUE THREAD

**Issue by devfreedom** [ashutoshgngwr/noice#189]
### Is your feature request related to a problem? Please describe.

Noice app utilizes certain type of sounds which leans toward a (mid-)high frequency band, such as sound of rain, chirping birds, sea wave, etc. But MP3 codec has a limited bandwidth and some encoders usually clip the frequency range above 16khz for compression. This leads to an audible loss of quality in such sounds. Unlike contemporary music, this is a playback in a loop, so it is even easier to notice the quality loss.

### Describe the solution you'd like

I wonder if it's possible to use Ogg Vorbis codec instead of MP3 file as long as Noice can handle a gapless loop playback of it. Ogg Vorbis is far superior to MP3 in many ways, especially when it comes to preserving (mid-)high frequency band. I think modern Android devices are powerful enough to handle an extra processing for Ogg Vorbis playback. Battery capacity is sufficient too. The downside would be negligible while the sound quality can be improved much better.

**Comment by ashutoshgngwr** [comment]
Hi @devfreedom! I am not an audio expert so I can't really tell if Vorbis will perform superior to MP3. But it should sure loop smoothly since [Android has native support for Vorbis media](https://developer.android.com/guide/topics/media/media-formats#audio-formats).

> But MP3 codec has a limited bandwidth and some encoders usually clip the frequency range above 16khz for compression.

While editing most of these sounds, I remember applying low-pass and high-pass filters somewhere within range 1.5kHz to 9kHz. I did this to remove the background hiss noise and maybe it's because of that.

At this point, given my expertise in audio, I can only say that this _might_ help in reducing the size of the app since OGG containers with Vorbis codec are known for their small output size compared to other formats.

PS, I am trying to keep my focus on things that relatively add more value to the project.

With all that said, if you can produce results where an average listener like myself is able to tell the difference or if it results in reduced app size, I'd be happy to accept the proposal.

**Comment by devfreedom** [comment]
https://en.wikipedia.org/wiki/Compression_artifact

> An example of compression artifacts in audio is applause in a relatively highly compressed audio file (e.g. 96 kbit/sec MP3). In general, musical tones have repeating waveforms and more predictable variations in volume, whereas applause is essentially random, therefore hard to compress. A highly compressed track of applause may have "metallic ringing" and other compression artifacts. `

https://www.soundonsound.com/techniques/what-data-compression-does-your-music

> The following example, from the Barclay Martin Ensemble's 'Eyes Of A Child', reveals how the stereo image and details carefully crafted by the recording, mix and mastering engineers are changed:
> 
> Audio Example L: A raw 16-bit/44.1kHz WAV file.
> Audio Example M: A 128kbps MP3 file.
> • The bongos panned hard left and right lose their crack and punch.
> • The shakers, panned to the left and right, and centred hi-hat lose their focused, 'point-source' precision. They become smudged or blurred horizontally, and sound a little distorted and crunchy.
> • The strummed chords on the acoustic guitar become grungey, and less crisp and detailed. The transparency, clarity, and energy is changed.
> • The bass towards the end is less full, and lacks its original power.
> • Overall, the stereo image loses its focus, precision and sense of envelopment.

This article explains how the compression of MP3 format impacts the sound quality. The most audible quality loss that people can easily hear would be something like hi-hat, shaker, and guitar chords which share a similar frequency band of the nature sounds I forementioned. I'm not talking about complaints from sound engineers. Average people can spot the difference quite easily while carefully listening to specific genres of music that MP3 encoder compresses the most.

According to CONTRIBUTING.md, the current standard of MP3 files for Noice app is

>     Sample rate: 44.1 kHz
>     Quality: Standard, 170-210 kbps
>     Variable Speed: Fast
>     Channel Mode: Stereo

and the bitrate around 200kbps is not good enough to deliver the maximum audio experience, which is a sole core functionality of Noice app, especially considering that users of this app can be hyperfocused on the sound quality itself when used for sleeping or productivity task in a quiet environment. Personally I find it quite irritating to keep noticing its MP3 compression artifact. For this reason, I think improving the sound quality should be the top priority - even at the cost of increased app size. 

Great app by the way, everything else is satisfying. Thank you.

**Comment by ashutoshgngwr** [comment]
@devfreedom Thank you for the detailed response. So far I am convinced how vorbis _may_ perform better than AAC. We already have a planned change for sound library in #62. This can be combined with that. Although I still don't understand how will we remove hiss noise from the background which is present in most of the source samples.

Right now I am caught up in other issues with #150 being the top priority. I'd love to see a helping hand. Let me know if you can take this up alongwith #62.

PS, most of the samples are MP3 encoded in their original source. Not sure how that would affect this. But we can always switch to a better source if the sample doesn't change by much.

**Comment by devfreedom** [comment]
> Right now I am caught up in other issues with #150 being the top priority.

Ah sure, priority as in "feature" not "development", I mean.

> most of the samples are MP3 encoded in their original source.
> #62

I think we need a new collection of high quality sound library then. Original sounds recorded in loseless format and then encoded in high efficiency modern codec. We can also use some publicly available high quality sound samples too, either open source license or public domain.

**Comment by ashutoshgngwr** [comment]
Right now, most of the sounds are from https://freesound.org and are CC-BY-SA licensed.

If you have any better suggestions, please let me know.

**Comment by octos** [comment]
What about Opus? It would allow higher quality at lower bitrates.

**Comment by ashutoshgngwr** [comment]
@octos I have very limited knowledge of audio codecs and from my initial reading, it seems like Opus is supposed to be the successor of Vorbis. If that's the case, Opus would make far more sense.

**Comment by devfreedom** [comment]
Opus also cuts audio above 20 kHz. Opus shares the similar limitation of MP3 in this case where none of it can properly preserve a high frequency band.

Opus is designed for high efficiency, not high fidelity. I think Ogg Vorbis is still the best option as long as we can get high quality audio sources which is above MP3 320K or OGG Q10. If the audio source is in maximum quality such as PCM/RAW, then we can even consider using FLAC.

In the end, it's all about original audio sources. Its quality determines the choice of codec Noice should use. If the source is not in good condition from the beginning, there is no point switching to a better lossy codec because it will need to be re-encoded and lose its quality even more.

**Comment by ashutoshgngwr** [comment]
@devfreedom Human ear is most sensitive in the range 2-5 kHz and not that sensitive to frequencies above 20 kHz. Along with that, I have to use low-pass filters (at around 8-12 kHz) to get rid of loud _hiss_ noise from the original samples. Both of these combined renders your concern irrelevant. I also found the following benchmark graph on [this Wikipedia Page](https://en.wikipedia.org/wiki/Opus_(audio_format)#Quality_comparison_and_low-latency_performance).

![opus comparision](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Opus_quality_comparison_colorblind_compatible.svg/1280px-Opus_quality_comparison_colorblind_compatible.svg.png)

FLAC is something that I wouldn't consider due to app size disadvantage.

**Comment by ashutoshgngwr** [comment]
Tested with both Vorbis and Opus. ExoPlayer doesn't [support gapless playback for Vorbis](https://github.com/google/ExoPlayer/issues/3470). In theory, Opus loops should work fine but I am still hearing a click sound at the loop end/start. Looks like we're stuck with MP3 because lossless formats will make the APK fat beyond normal.

**Comment by resolritter** [comment]
I was about to open an issue on a similar tone. I was noticing the audio was "stuttering" between loops, so my first idea was to try to remove the silence gaps in gaps on Audacity... Only to find out that's "very difficult" (and definitely beyond my comprehension) to do with MP3.

[Unwanted silence added after exporting in MP3](https://forum.audacityteam.org/viewtopic.php?t=72595)

[Additional link](https://forum.audacityteam.org/viewtopic.php?p=213658#p213660); quoted

> It is a limitation of the MP3 format that there is always a little leading silence. http://wiki.audacityteam.org/wiki/MP3#Limitations
For looping without a gap you need to use a different format such as WAV or OGG.

@ashutoshgngwr 

> Looks like we're stuck with MP3 because lossless formats will make the APK fat beyond normal.

I'd definitely take a size gain over having those leading/trailing silences which break immersion.

Regarding the format: have you considered doing WAV?

Regarding the size: have you considered an add-on architecture? One app I know which does this is "AnySoftKeyboard". Instead of bundling all the languages into the main app, it offers the user the option to install languages as extensions through other APKs.

For instance, this is the main app: https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard

And languages are add-ons: https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.indonesian

Similarly, you could bundle the MP3 into the app and have the gapless sounds as an add-on which is distributed separately. Although, if that sounds too complicated, I'm in favor of just outright replacing the current sounds.

**Comment by ashutoshgngwr** [comment]
@resolritter 

> I was about to open an issue on a similar tone. I was noticing the audio was "stuttering" between loops, so my first idea was to try to remove the silence gaps in gaps on Audacity... Only to find out that's "very difficult" (and definitely beyond my comprehension) to do with MP3.
>
> I'd definitely take a size gain over having those leading/trailing silences which break immersion.

I have taken extreme precautions to remove the stuttering in loops and all loops are stutter-free in the latest versions as far as I know. Yes, MP3 encodes silence at the start and end of the audio track; it is part of the encoding and a good decoder takes it into account. e.g., Exoplayer automatically trims that silence on decode but Audacity (for whatever reasons) doesn't. So if you re-open a sample in Audacity, the silence is visible and you'd have to manually remove it.

> Regarding the format: have you considered doing WAV?

I prefer MP3 over WAVs because quality-wise, WAV creates no value at all in our scenario. Many source samples themselves were encoded to MP3 from the scratch which makes it rather pointless to re-encode them using WAV.

> Regarding the size: have you considered an add-on architecture? One app I know which does this is "AnySoftKeyboard". Instead of bundling all the languages into the main app, it offers the user the option to install languages as extensions through other APKs.

The size matters because many users in developing nations use mobile data as their primary source of internet connectivity. These are limited and cost more than ISP broadband plans. For instance, I was one of such users until last year and the majority population in my country uses mobile data. While [APK expansion pack](https://developer.android.com/google/play/expansion-files) is the next logical step, I would want to delay it unless the size crosses Play Store's threshold (which is around 100 MBs AFAIK).

On the other hand, the add-on idea sounds interesting and I'd love to continue discussing it in a new thread altogether. This will also partially address the concerns raised in #142.
