### ISSUE TITLE
Make Saved Presets editable. 

### ISSUE THREAD

**Issue by llewlem888** [ashutoshgngwr/noice#328]
It seems impossible to edit saved presets.

**Comment by ashutoshgngwr** [comment]
1. Play a preset
2. Edit its settings from the library
3. Save it under a different name

And edit option will also need a similar effort from users' side but with different terminology.

Please let me know if this resolves the issue.

**Comment by Mickael-Martin** [comment]
Another solution : Maybe you can add a button "edit" at the same place as rename and delete witch go the the library menu and display a toolbox with "Change your mix and save", the button "save" display by default the selected preset and the user can overwrite a preset with the same name (with confirmation).
But it's a big work I thing.

**Comment by ashutoshgngwr** [comment]
@Mickael-Martin while the flow is very straightforward, requires a lot of change in existing flows compared to the value added. Besides, when editing a preset, it would be desirable to have it playing so that one could get instant feedback on adjustments. It again pretty much boils down to what I mentioned earlier.

I'll keep the issue open and try explore the idea. As of now, I can't think of a way that performs more efficiently than what we have now (although what we have now isn't really intuitive).

Also as a note to self, current renaming flow doesn't offer overwriting a preset.
