### ISSUE TITLE
Document the process of applying equalization in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Lesik** [ashutoshgngwr/noice#419]
### Is your feature request related to a problem? Please describe.
Some (21 of 35 as of 2020-11) sounds in this repo are equalized (#313). When adding or modifying sounds, equalization should be applied to them. This process should be documented in CONTRIBUTING.md.

### Describe the solution you'd like
A step-by-step guide on how to equalize sounds, that is easily understood even by contributors who are not familiar with Audacity.

### Additional context
This comment describes the process somewhat, but is not easy to understand: https://github.com/ashutoshgngwr/noice/issues/227#issuecomment-685164223

**Comment by Lesik** [comment]
As of 2020-11, @ashutoshgngwr noted that not all sounds produce acceptable results when equalized. The following command might be of help, which, when run in the root of the repo, prints the file paths of all the sounds that @ashutoshgngwr deemed equalizable and writes them to a file. Audacity can then be instructed to open the files as separate tracks in one window, instead of one window per file.

```sh
$ git diff-tree 2ce730c08992b50c27923a752dd2e36b89499574 --name-only --no-commit-id -r | awk -v pwd="$PWD" '{print "file \""pwd"/"$1"\""}' > audacity.lof
$ audacity audacity.lof
```

**Comment by Lesik** [comment]
@GittyBruce According to my understanding, loudness normalization level is related to the input sounds it is applied on. If you apply it on two files of which one is very loud and the other very quiet, it will normalize both to a middle level. If it is applied on two loud or quiet files, they will (mostly) retain their loudness because on a relative scale, there is (almost) nothing to normalize. Therefore, equalization must be applied to all (eligible) sounds in the library, so that they all match each other. Am I wrong here?

**Comment by ashutoshgngwr** [comment]
@Lesik - @GittyBruce implied applying the compressor effect. AFAIK, it tries to minimise the gap between the highest and lowest amplitude of the sound wave. The following excerpt is from Wikipedia:

> an audio signal processing operation that reduces the volume of loud sounds or amplifies quiet sounds, thus reducing or compressing an audio signal's dynamic range.

From what I've observed, the end result is a bit more smooth on the ear. IMO, it's not necessary to apply the effect on each and every sample. It can be applied if the end result sounds better than the source.

> As of 2020-11, @ashutoshgngwr noted that not all sounds produce acceptable results when equalized.

This happened because I applied a macro to all the sounds to avoid manually opening and applying the effect. As a result of this batch processing, some perfectly looping sounds ended up having weird silence (not complete silence but a slight reduction in volume) at their edges. Having limited time at hand, I omitted them from the commit at the time.

As for the settings, you can either play with them to find the sweet spot or use the settings suggested by @GittyBruce in the original comment. As far as I remember, the suggested settings produced a very decent output compared to the other settings that I tried at the time.

**Comment by ashutoshgngwr** [comment]
Hey @Lesik 

I went ahead and made all the changes. I've also reverted the 3 beep sample to the old 2 beep sample. https://github.com/ashutoshgngwr/noice/commit/654a2c9c58d8fa1a7321186847e055789f1d61d5

**Comment by Lesik** [comment]
Thanks!
