### ISSUE TITLE
Playing sounds dampens music from other app

### ISSUE THREAD

**Issue by pizzapim** [ashutoshgngwr/noice#462]
### Describe the bug

I wanted to have music playing and sounds from the Noice app simultaneously, but it dampens the music of the other app. It only happens the first time I play a sound. If I stop and then restart the sound, the music is not dampened.

### To Reproduce
1. Play some music from another app (Spotify in this case)
2. Stop and start the Noice app
3. Press a sound to make it play
4. The music in the background is now dampened
5. Stop and start the sound again
6. The music in the background is not dampened this time

### Expected behavior
I expect the music in the background to continue playing at the same volume at all times.

### Others
 - Device: Motorola Moto 5
 - Android Version: 8.1.0
 - App version: F-Droid 0.14.0

**Comment by ashutoshgngwr** [comment]
I am able to reproduce the issue. I'll further investigate it later.

**Comment by ashutoshgngwr** [comment]
I have fixed the underlying bug, and it doesn't satisfy your specific requests. The dampening of sound is the expected behaviour. Noice requests _partial audio focus_ before playing any media. The Android framework dampens the sound of the other player to comply with this request. The issue was that once Noice abandoned the audio focus, it wasn't re-requesting it again. Hence, the other music player was not dampening the second time. I've addressed this issue.

As for your concern, it is an enhancement to the project at this stage. In future, we can give users the ability to disable audio focus management. The Android framework doesn't complain when an app plays media without requesting the audio focus, but it isn't _the right way of doing things_.
