### ISSUE TITLE
Purring Cat sound has mouse clicking and other household noise

### ISSUE THREAD

**Issue by pieterjoanUvA** [ashutoshgngwr/noice#463]
### Is your feature request related to a problem? Please describe.
I really love the purring feline sounds, since it remembers me of my house-cat Poema, a small full-black female cat that lived around our house, sometimes went on the roof to look down on the neighbourhood, and was fun to play with.

### Describe the solution you'd like
Maybe a try to re-record, or re-edit the sample, since the purring is excellent, the clicking has for my usecase a distracting attention deficit.

### Additional context
Feel free to not do this, ofcourse. Please do just delete this one, if you are offended or feel the need to answer with 'yes'.
And since I live in an appartment on the second floor and my persuasion that a cat should be able to travel outside at the will of the cat itself, and a stair towards the surrounding grass is not a practical solution, this would be a nice substitute for not having an inside_house_cat.

Also I am a fond user of your 10-bit clock widget, though reading is still not re-learned again,
since i had to learn that in my Informatics education, obliged....

With kind regards,
Pieter Joan

**Comment by pieterjoanUvA** [comment]
Thank you for your efforts. 
With kind regards, Pieter Joan

**Comment by ashutoshgngwr** [comment]
Hey @pieterjoanUvA 

I didn't think you were active on GitHub. I tried to remove as much disturbance from the sample as I could. You can still hear some deep hiss noise caused by the movement of the microphone. Unfortunately, it is present all over the original sample and I couldn't remove it. Let me know what do you think of the updated sample. You can listen to it [here](https://github.com/ashutoshgngwr/noice/raw/d7cced109f36fcb5d8a88d1bf02ec0033880435f/app/src/main/assets/purring_cat.mp3).
