### ISSUE TITLE
Bringing it natively to Linux.

### ISSUE THREAD

**Issue by HolySoap** [ashutoshgngwr/noice#487]
I would love to see this fantastic piece of software running natively on Linux and not just on mobile. Are there any plans or can you consider it in the future?

The best way (I think) would be trough [Flathub](https://flathub.org/home) and how you submit can be found [here on GitHub](https://github.com/flathub/flathub/wiki/App-Submission), the front and backend is fully open-source.

There is already a similar program called [Blanket](https://flathub.org/apps/details/com.rafaelmardojai.Blanket), but it isn't really comparable.

**Comment by ashutoshgngwr** [comment]
Not possible to port Noice to any other operating system since the client is written using native Android SDK. The best bet is to write a controller web-app to control the [Chromecast receiver app](https://github.com/ashutoshgngwr/noice/tree/master/cast-receiver) [[Docs](https://github.com/ashutoshgngwr/noice/blob/master/docs/CONTRIBUTING.md#cast-receiver)].

**Comment by ashutoshgngwr** [comment]
I am moving this issue to the discussions for now since it's neither planned nor in the current scope of this project.

Also related to issue https://github.com/ashutoshgngwr/noice/issues/399.

**Comment by ashutoshgngwr** [comment]
Hey @HolySoap! An early prototype for a web application of Noice is now available. You can try it at https://app.trynoice.com. The source code is available at https://github.com/trynoice/web-app-v0.
