### ISSUE TITLE
Wake up timer resets time after changing preset

### ISSUE THREAD

**Issue by nitrocode** [ashutoshgngwr/noice#504]
# Is your feature request related to a problem? Please describe.

I noticed that when I want to set a wake up timer, I set the time first and then I set the preset and that would reset my time to the original value instead of the value that I had previously set.

# Describe the solution you'd like

Keep the time the same even if the preset is changed.

I also only have a single preset. The app could set that as my default unless I have more than one preset saved. In that case, it could still default to the first one in the list.

**Comment by robercoding** [comment]
Hi @ashutoshgngwr,

I'd like to contribute for the first time to an open source project, could you assign me this task and try to implement a solution?

**Comment by robercoding** [comment]
Hi @ashutoshgngwr,

I'd like to contribute for the first time to an open source project, could you assign me this task and I try to implement a solution?

**Comment by ashutoshgngwr** [comment]
Hey @robercoding! If possible, please also add a test-case demonstrating the faulty behaviour so that it doesn't break with future changes.

**Comment by robercoding** [comment]
Hey @ashutoshgngwr! It has been a while since you assigned me this task and I started working on it 3-4 days ago, I implemented a solution for this feature and it's working perfectly! but **when trying to add some Instrumented Test Cases** on `WakeUpTimerFragmentTest` there's an error that looks like it was there before I started and I tried to solve it with no luck.

The error I found is related to MockK:
`io.mockk.MockKException: Failed matching mocking signature for left matchers: [any(), any()]`

[This error happens right here ](https://github.com/ashutoshgngwr/noice/blob/master/app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/WakeUpTimerFragmentTest.kt#L54)

I've looked up all around the internet and my thoughts are that is related with some inline problems/Mockk can't mock them. Could you tell me if those instrumented test cases are working for you? If yes, have you faced this problem before? 

What should I do? Meanwhile I'll keep looking for a solution!

**Comment by ashutoshgngwr** [comment]
Hey @robercoding! I forgot that I had assigned you this issue. Last Sunday, I did some refactoring to make room for new features. It's likely that your changes will be undone during the implementation of the new features.

The good news is that I don't know how the roadmap looks. In the meantime, can you open up a draft pull request against [`idk-what-i-am-doing`](https://github.com/ashutoshgngwr/noice/tree/refactor/idk-what-i-am-doing) branch? It'll help me understand what we can do to merge your work in my working branch.

As for your issue, I think it's happening because the test you've written specified an expected call to the mock (in `setup` method), but the method wasn't called during the test so mock is complaining about it. I'll have a clearer picture once I have a look at your code.

Also, please let me know if you'll be interested in working on new features.

**Comment by robercoding** [comment]
Hi @ashutoshgngwr! 
Sure I'll open a DF pull request now to that new branch, it tells me that is able to merge so that's good, and for the test case I haven't implemented it yet since I spent time trying to understand what's going on with that error before moving on. 

Anyways I for sure would like to keep contributing and gaining more experience so if you see a task for me or you want help just tell me, also I'll keep an eye around looking for issues that I can work on!

**Comment by ashutoshgngwr** [comment]
Fixed in #543
