### ISSUE TITLE
make random mode more prominent

### ISSUE THREAD

**Issue by anarcat** [ashutoshgngwr/noice#537]
### Is your feature request related to a problem? Please describe.

I recently found out about the "random" feature, which seems to pop up as a little button on the bottom right. It's pretty neat!

Yet I can't figure out how to bring it back! If I start playing some sounds, it disappears and gets replaced by the "disk" icon to save the presets...

### Describe the solution you'd like

It would be nice if the button would always be there, or be available in the "hamburger menu" for example.

**Comment by ashutoshgngwr** [comment]
Will try to fix it. Meanwhile, to bring the button back, stop the playback. It should come back up when no sounds are playing.

**Comment by anarcat** [comment]
thanks for the tip!

**Comment by robercoding** [comment]
Hey @ashutoshgngwr I want to try to fix this if you are not working on it, and also talk about the best solution for UX!

Somehow I feel like this random mode should be always available so we could make fab button have to open 2 fab buttons to the top when is in random mode is active, giving user the two options.
Or just 2 fab buttons, so save preset option only appears when sound is playing. 

Let me know your thoughts and if you have other possible implementations!

**Comment by ashutoshgngwr** [comment]
Hey @robercoding,

I was thinking of moving the random preset option to the navigation menu on the left.

I wanted it to do it this way because I was also planning to add an option that would allow users to automatically change random presets at whatever interval they decide, e.g. change random preset every 15 minutes or so. We can probably add it later. For now, just move the option from FAB to navigation bar.
