### ISSUE TITLE
 "On-Screen-Menu- Buttons" do not react to Android Dark Mode

### ISSUE THREAD

**Issue by Watson15683** [ashutoshgngwr/noice#556]
### Is your feature request related to a problem? Please describe.
The "On-Screen-Menu" does not react to dark mode. After having activated dark mode the "On-Screen-Menu" stays white.

This is how the noice-App it looks like with Dark Mode activated:
![grafik](https://user-images.githubusercontent.com/79628154/110940692-94ee0980-8337-11eb-8bae-5545770ce52c.png)

This is how i think it is supposed to look like (Screenshot taken from the Nextcloud-App in Dark mode)
![grafik](https://user-images.githubusercontent.com/79628154/110941113-19408c80-8338-11eb-8ba2-2a4cb8f77bb7.png)

### to replicate

1. Have a Phone with "On-Screen-Menu"
2. activate Dark Mode
3. Look at the "On-Screen-Menu"

### Describe the solution you'd like
Id like the app to change the colour of the  "On-Screen-Menu", when the Dark mode is activated, to the background colour of the app. Because the white colour is not that pleasing on the eyes at night.

### Additional Information

- Device: Samsung Galaxy M21
- Android Version: Android 10
- One UI Core-Version: 2.5
- App Version: 0.15.0 (F-Droid)

**Comment by ashutoshgngwr** [comment]
Likely happening due to the dark action bar feature. Earlier, the navigation bar used to translucent, but that had to change in light of #484. Now I am thinking of removing the dark action bar feature altogether, and making it a light action bar with the light theme variant and dark action bar with the dark theme variant.
