### ISSUE TITLE
Add some pre-defined presets

### ISSUE THREAD

**Issue by markwmuller** [ashutoshgngwr/noice#720]
### Is your feature request related to a problem? Please describe.
No
### Describe the solution you'd like
For a firs-time user, it'd be nice if there were some examples of "good" presets that one can just use (my use case -- baby crying incessantly, I search for "noise" on f-droid, find "Noice", and just want to launch into some noise). Of course, it's not super hard to make something reasonable, but a new user would benefit from some presets (that's where I immediately went in the app, but was disappointed that there's nothing there).

**Comment by ashutoshgngwr** [comment]
This had been discussed before, but the discussion eventually died due to a lack of enthusiasm. I shouldn't be the only person to come up with this list of presets. It leaves the list prone to being too similar. If you could suggest a few, that'd be great.

Or perhaps there should be some sort of popularity vote. I am integrating analytics into Play Store build for Noice. I shall soon have enough data to judge general preferences and come up with a generic list.

**Comment by markwmuller** [comment]
I'm happy to share what I made, a thunderstorm -- It's very simple, just heavy rain, plus the thunder, all at 100% volume with somewhat arbitrary repeat time periods. 

https://ashutoshgngwr.github.io/noice/preset?name=Thunderstorm%20&playerStates=%5B%7B%22soundKey%22%3A%22distant_thunder%22%2C%22timePeriod%22%3A219%2C%22volume%22%3A20%7D%2C%7B%22soundKey%22%3A%22heavy_rain%22%2C%22timePeriod%22%3A300%2C%22volume%22%3A20%7D%2C%7B%22soundKey%22%3A%22rolling_thunder%22%2C%22timePeriod%22%3A294%2C%22volume%22%3A4%7D%2C%7B%22soundKey%22%3A%22thunder_crack%22%2C%22timePeriod%22%3A337%2C%22volume%22%3A17%7D%5D

**Comment by eMPee584** [comment]
Here's a beach one:
https://ashutoshgngwr.github.io/noice/preset?name=%F0%9F%8F%9D%EF%B8%8F&playerStates=%5B%7B%22soundKey%22%3A%22crickets%22%2C%22timePeriod%22%3A300%2C%22volume%22%3A4%7D%2C%7B%22soundKey%22%3A%22screeching_seagulls%22%2C%22timePeriod%22%3A300%2C%22volume%22%3A4%7D%2C%7B%22soundKey%22%3A%22seaside%22%2C%22timePeriod%22%3A300%2C%22volume%22%3A13%7D%2C%7B%22soundKey%22%3A%22wind_in_palm_trees%22%2C%22timePeriod%22%3A300%2C%22volume%22%3A10%7D%5D
